version: '3.8'

services:
  backend-api:
    build: ./backend-api
    ports:
      - "7860:7860"
    env_file: .env
    volumes:
      - ./backend-api:/app
    command: streamlit run app.py --server.port=7860 --server.address=0.0.0.0

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
